### ISSUE TITLE
Zig finds unreachable code when running test

### ISSUE THREAD

**Issue by VisenDev** [bluesillybeard/zig-interface#3]
I was working on trying to implement a more concrete example of how this library would be used, however, zig is panicking when I try to compile and run the test

I'm not sure if this is user error or if I am missing something

Here is the failing test case
```zig
const std = @import("std");
const testing = std.testing;
const interface = @import("interface");

//=============Code to create the interface=============
fn MakePrintable(comptime BaseType: type) type {
    return struct {
        pub inline fn to_string(self: BaseType, a: std.mem.Allocator) ![]u8 {
            return self.vtable.to_string(self.object, a);
        }
    };
}
// makeInterface creates an interface type that can be used to create implementations
const Printable = interface.MakeInterface(MakePrintable, .{});

//==============Code to create a type which implements the interface==========
const SubType = struct {
    foo: i32,
    bar: i32,

    pub fn to_string(self: @This(), a: std.mem.Allocator) ![]u8 {
        return try std.fmt.allocPrint(a, "[foo: {}, bar: {}]", .{ self.foo, self.bar });
    }
};

//==============Code to create a function which accepts the interface type===========
fn doSomething(a: std.mem.Allocator, printable: Printable) !void {
    const string = try printable.to_string(a);
    defer a.free(string);
    std.debug.print("{s}", .{string});
}

test "printable interface" {
    var sub_type_value = SubType{ .foo = 123, .bar = 456 };
    var sub_type_interface = Printable.initFromImplementer(SubType, &sub_type_value);

    const stringified = try sub_type_interface.to_string(std.testing.allocator);
    defer std.testing.allocator.free(stringified);

    try doSomething(std.testing.allocator, sub_type_interface);
}
```

[output.txt](https://github.com/bluesillybeard/zig-interface/files/13692999/output.txt)

**Comment by VisenDev** [comment]
I'm not really sure how to debug this since I can't even get it to compile and show a diagnostic, the compiler just panics. Maybe I've got a syntax error but I am not sure

**Comment by VisenDev** [comment]
Doing some more testing with commenting different sections out, I was able to find that there is an issue with the `to_string` functions having different return types. Probably an issue with the inferred error sets being different.

**Comment by VisenDev** [comment]
Actually, you know what I bet the zig compiler was trying falling into a circular dependency trying to infer the error sets. That might have been the problem. Thats why it failed to compile. 

Changing the `![]u8` to `?[]u8` now seems to work

**Comment by bluesillybeard** [comment]
A decent solution to stop others from trying to use inferred error sets is to add a check to the `makeInterface` function.
